# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umapp', '0003_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marker',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
