# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umapp', '0004_auto_20171104_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
