# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umapp', '0008_marker_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('marker_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umapp.marker')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umapp.user')),
            ],
        ),
    ]
