# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umapp', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='entrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_suffix', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('ramp_access', models.BooleanField(default=False)),
                ('powered_doors', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umapp.disability')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='entrance',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umapp.location'),
        ),
    ]
