# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umapp', '0010_auto_20171104_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umapp.entrance')),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umapp.location')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umapp.user')),
            ],
        ),
    ]
